const  USER_TYPE = {
    FUNCIONARIO: 0,
    FUNCIONARIO_NAME: 'FUNCIONÁRIO',
    ALUNO: 1,
    ALUNO_NAME: 'ALUNO',
    EMPRESA: 2,
    EMPRESA_NAME: 'EMPRESA',
    ARRAY: []
};

USER_TYPE.ARRAY.push({id:USER_TYPE.FUNCIONARIO , name:USER_TYPE.FUNCIONARIO_NAME });
USER_TYPE.ARRAY.push({id:USER_TYPE.ALUNO , name:USER_TYPE.ALUNO_NAME });
USER_TYPE.ARRAY.push({id:USER_TYPE.EMPRESA , name:USER_TYPE.EMPRESA_NAME });
export { USER_TYPE }

const STATUS = {
    ATIVO: 1,
    ATIVO_NAME: "ATIVO",
    INATIVO: 0,
    INATIVO_NAME:"INATIVO",
    ARRAY: []
};

STATUS.ARRAY.push({id: STATUS.ATIVO, name:STATUS.ATIVO_NAME});
STATUS.ARRAY.push({id: STATUS.INATIVO, name:STATUS.INATIVO_NAME});
export { STATUS }

const VACANCY_TYPE = {
    CLT: 0,
    CLT_NAME: "CLT",
    ESTAGIO: 1,
    ESTAGIO_NAME: "ESTÁGIO",
    ARRAY: []
}

VACANCY_TYPE.ARRAY.push({id: VACANCY_TYPE.CLT, name:VACANCY_TYPE.CLT_NAME});
VACANCY_TYPE.ARRAY.push({id: VACANCY_TYPE.ESTAGIO, name: VACANCY_TYPE.ESTAGIO_NAME});

export { VACANCY_TYPE }

const REMUNERATION = {
    REMUNERADO: 1,
    REMUNERADO_NAME: "REMUNERADO",
    NAO_REMUNERADO: 0,
    NAO_REMUNERADO_NAME: "NÃO REMUNERADO",
    ARRAY: []
}

REMUNERATION.ARRAY.push({id: REMUNERATION.REMUNERADO, name:REMUNERATION.REMUNERADO_NAME});
REMUNERATION.ARRAY.push({id: REMUNERATION.NAO_REMUNERADO, name:REMUNERATION.NAO_REMUNERADO_NAME});

export { REMUNERATION }