const  USERTYPE = {
    FUNCIONARIO: 0,
    FUNCIONARIO_NAME: 'FUNCIONÁRIO',
    ALUNO: 1,
    ALUNO_NAME: 'ALUNO',
    EMPRESA: 2,
    EMPRESA_NAME: 'EMPRESA',
    ARRAY: []
};

USERTYPE.ARRAY.push({id:USERTYPE.FUNCIONARIO , name:USERTYPE.FUNCIONARIO_NAME });
USERTYPE.ARRAY.push({id:USERTYPE.ALUNO , name:USERTYPE.ALUNO_NAME });
USERTYPE.ARRAY.push({id:USERTYPE.EMPRESA , name:USERTYPE.EMPRESA_NAME });
export { USERTYPE }

const STATUS = {
    ATIVO: 1,
    ATIVO_NAME: "ATIVO",
    INATIVO: 0,
    INATIVO_NAME:"INATIVO",
    ARRAY: []
};

STATUS.ARRAY.push({id: STATUS.ATIVO, name:STATUS.ATIVO_NAME});
STATUS.ARRAY.push({id: STATUS.INATIVO, name:STATUS.INATIVO});
export { STATUS }

const VACANCYTYPE = {
    CLT: 0,
    CLT_NAME: "CLT",
    ESTAGIO: 1,
    ESTAGIO_NAME: "ESTÁGIO",
    ARRAY: []
}

VACANCYTYPE.ARRAY.push({id: VACANCYTYPE.CLT, name:VACANCYTYPE.CLT_NAME});
VACANCYTYPE.ARRAY.push({id: VACANCYTYPE.ESTAGIO, name: VACANCYTYPE.ESTAGIO_NAME});

export { VACANCYTYPE }

const REMUNERATION = {
    REMUNERADO: 1,
    REMUNERADO_NAME: "REMUNERADO",
    NAO_REMUNERADO: 0,
    NAO_REMUNERADO_NAME: "NÃO REMUNERADO",
    ARRAY: []
}

REMUNERATION.ARRAY.push({id: REMUNERATION.REMUNERADO, name:REMUNERATION.REMUNERADO_NAME});
REMUNERATION.ARRAY.push({id: REMUNERATION.NAO_REMUNERADO, name:REMUNERATION.NAO_REMUNERADO_NAME});

export { REMUNERATION }